### ISSUE TITLE
Optimization warning

### ISSUE THREAD

**Issue by griff4692** [patil-suraj/question_generation#13]
Thanks for making this repo!

```
UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
```

Is this something we should adjust for or is this intentional?  I'm also curious as to what hyperparameter tuning has been done. the effective fine-tuning batch size is about 256 (GAS * BS).  I'm wondering how that number was arrived at!

**Comment by patil-suraj** [comment]
Hi @griff4692 ,
You can safely ignore this warning. 

No special hyperparameter tuning has been done. The BS is chooses by following the current trends and the max the GPU can fit. All of these models are trained on  single V100 (16 GB)

**Comment by griff4692** [comment]
Thanks for sharing this information!
