### ISSUE TITLE
Regarding Fine-Tuning

### ISSUE THREAD

**Issue by khushgrover** [patil-suraj/question_generation#16]
Hey! Awesome work!
I wanted to ask how have you actually fine tune on the SQuAD dataset? I couldn't find it here.
i was trying to understand the valhalla/t5-base-e2e-qg model.

**Comment by patil-suraj** [comment]
Thanks @khushgrover ,

For end-to-end qg, all questions for a single passage are joined using the `<sep>` token and given as a single example.

So if the passage is like
`Python is a programming language. Created by Guido van Rossum and first released in 1991.`

and the question are 
```
Who created Python  ?
When was python released ?
```
Then example is prepared as 

input text: `Python is a programming language. Created by Guido van Rossum and first released in 1991.`

target text: `Who created Python ? <sep> When was python released ? <sep>`.

Also the dataset is provided using the `nlp` library so the processing is handled there. You can view the data using

```python3
data = nlp.load_dataset("data/squad_multitask", name="highlight_qg_format", split=nlp.Split.TRAIN) # this will load data for all tasks
data = data.filter(lambda example:  example['task'] == 'e2e_qg')
```

Let me know if you need more info.

**Comment by katirasole** [comment]
Thank you very much for your works. I read an article that was mentioned about  highlight format. Maybe the following article is that you've mentioned. 
https://www.aclweb.org/anthology/D19-5821/

**Comment by patil-suraj** [comment]
Thanks @katirasole . This was the paper I was looking for. Thank you very much !

**Comment by SaakshiNarula** [comment]
Hey, thanks for the further info on Fine Tuning. So to clarify, if I am to train it on the Squad dataset, I just need to use the two lines you mentioned above followed by the run_qg(args_dict) section mentioned in fine tuning (i.e no need to use prepare.py here right?) 
Because I tried that and am getting this error. not sure what needs to be modified..
![image](https://user-images.githubusercontent.com/62864994/89514921-8959c380-d7e7-11ea-96db-6d6a0198d126.png)

**Comment by patil-suraj** [comment]
Hi @SaakshiNarula ,
You'll need to prepare the data, before fine_tuning. `prepare_data.py` adds the new special tokens in the tokenizer and saves it, processes and caches the data according to the format and task you provided via args. You can specify the task using the `--task` argument (one of "qg", "qa", "e2e_qg", "multi", "ans_ext") and qg format using the `--qg_format` argument (one of "prepend_qg_format", "highlight_qg_format").

Hope this helps.

**Comment by khushgrover** [comment]
Closed
