### ISSUE TITLE
GPU OOM

### ISSUE THREAD

**Issue by tomwilde** [patil-suraj/question_generation#2]
Hi, 

this is really great, thx for sharing. As per title I have limited GPU memory, any pointers on getting it to work ok?

thanks again.

**Comment by patil-suraj** [comment]
Hi @tomwilde , Thanks you !

Can tell me how much GPU memory you have and which model you were using ?

Also when did it gave the OOM error, at the first run or after loading multiple models ?

**Comment by tomwilde** [comment]
Hi, it’s a 750Ti with a whole 2Gb of ram. The model load fails but I didn’t think it was that big. 

Thanks again

Tom

**Comment by patil-suraj** [comment]
Hmm, t5 small should load in 2gb of ram. I'll need few more details, which pipeline are you using ? Also small modor or base model ?

**Comment by tomwilde** [comment]
Hi, so its super simple!

from  question_generation.pipelines import pipeline
nlp = pipeline("question-generation")
testText = "some text in here"
print(nlp(testText))

Which gives me the traceback:

(tensorflow) H:\Projects\Python\question-generation>python hosted.py
Traceback (most recent call last):
  File "hosted.py", line 10, in <module>
    print(nlp(testText))
  File "H:\Projects\Python\question-generation\question_generation\pipelines.py", line 63, in __call__
    questions = self._generate_questions(qg_inputs)
  File "H:\Projects\Python\question-generation\question_generation\pipelines.py", line 74, in _generate_questions
    num_beams=4,
  File "C:\Users\Tom\Anaconda3\envs\tensorflow\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Tom\Anaconda3\envs\tensorflow\lib\site-packages\transformers\modeling_utils.py", line 1229, in generate
    model_specific_kwargs=model_specific_kwargs,
  File "C:\Users\Tom\Anaconda3\envs\tensorflow\lib\site-packages\transformers\modeling_utils.py", line 1548, in _generate_beam_search
    past = self._reorder_cache(past, beam_idx)
  File "C:\Users\Tom\Anaconda3\envs\tensorflow\lib\site-packages\transformers\modeling_t5.py", line 1190, in _reorder_cache
    layer_past_state.index_select(0, beam_idx),
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 2.00 GiB total capacity; 1.35 GiB already allocated; 32.23 MiB free; 1.37 GiB reserved in total by PyTorch)

**Comment by patil-suraj** [comment]
Hi, I see what the issue is, the question-generation pipeline actually loads two models, one for extracting answer and other for generating question and both models are loaded on GPU at the same time. This can be made more efficient by loading the model on GPU only when it's used. 

Till then try the multitask pipeline, it uses single model for both answer extraction and que generation and it's performance is also slightly better than single task t5 small.

Let me know if you still run into oom even with single t5 small

**Comment by tomwilde** [comment]
Hi again, so multitask proved too big too. So I went ahead and added a cpu-only option to pipelines and have raised a PR for it.

Thanks for you help anyway!

https://github.com/patil-suraj/question_generation/pull/5
