### ISSUE TITLE
using question_generation directly from /transformers

### ISSUE THREAD

**Issue by vidyap-xgboost** [patil-suraj/question_generation#21]
Hi, 

I'm pretty new to using huggingface/transformers.

I have seen that this repo has an [API to play with](https://huggingface.co/valhalla/t5-small-qa-qg-hl) on huggingface website.

I'm not understanding how to use this directly from the library.

This is my code:

```python
from transformers import pipeline

from transformers import AutoTokenizer, AutoModelWithLMHead

singletask_tokenizer = AutoTokenizer.from_pretrained("valhalla/t5-small-qg-hl")

singletask_model = AutoModelWithLMHead.from_pretrained("valhalla/t5-small-qg-hl")

input_ids = singletask_tokenizer.encode(text)
```

Now, running this code gives me following error:

```python
singletask_model.generate(input_ids=input_ids)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-0f839014ebe9> in <module>()
----> 1 singletask_model.generate(a)

1 frames
/usr/local/lib/python3.6/dist-packages/transformers/generation_utils.py in generate(self, input_ids, max_length, min_length, do_sample, early_stopping, num_beams, temperature, top_k, top_p, repetition_penalty, bad_words_ids, bos_token_id, pad_token_id, eos_token_id, length_penalty, no_repeat_ngram_size, num_return_sequences, attention_mask, decoder_start_token_id, use_cache, **model_specific_kwargs)
    278 
    279         if input_ids is not None:
--> 280             batch_size = input_ids.shape[0]  # overriden by the input batch_size
    281         else:
    282             batch_size = 1

AttributeError: 'list' object has no attribute 'shape'
```

How should I go about this?

**Comment by patil-suraj** [comment]
Hi @vidyap-xgboost ,
`input_ids` should be a batch of `Tensor` and not `list`. pass the `return_tensor=pt` parameter to `tokenizer` and it will return `input_ids` as `Tensor`.

```python3
enc = tokenizer([text], return_tensor="pt")
input_ids = enc["input_ids"]
attention_mask = enc["attention_mask"] # necessary if padding is enabled so the model won't attend pad tokens
singletask_model.generate(input_ids=input_ids, attention_mask=attention_mask)
```

**Comment by vidyap-xgboost** [comment]
Hello @patil-suraj , Thanks for the quick reply and the clarification.

When I run the following code:

```python
enc = tokenizer([text], return_tensor="pt")
input_ids = enc["input_ids"]
attention_mask = enc["attention_mask"] 
```

I get this error:

```python
Keyword arguments {'return_tensor': 'pt'} not recognized.
```

Hence, it's not able to run `singletask_model.generate(input_ids=input_ids, attention_mask=attention_mask)`

**Comment by vidyap-xgboost** [comment]
How to use `.decode` method to return the questions and answers? @patil-suraj

**Comment by vidyap-xgboost** [comment]
@psinha30 this looks really helpful! Thank you. I shall try this and update here.

**Comment by psinha30** [comment]
> @psinha30 this looks really helpful! Thank you. I shall try this and update here.
> 
> Also, could you tell me how to return more than one question using the `.decode` method?

use this for more than 1 question:
tokens = model.generate(input_ids=input_ids, attention_mask=attention_mask,num_beams=6,num_return_sequences = 5)
out_ = []
for token in tokens:
    print(tokenizer.decode(token))
    out_.append(tokenizer.decode(token))
Note: num_beams >= num_return_sequences

**Comment by vidyap-xgboost** [comment]
@psinha30 Thank you! This works and also, using `<hl>` solves the problem for texts it wasn't able to create questions. However, according to the examples given in the README file, we shouldn't be giving any highlights in the first place. I understand that @patil-suraj is working on resolving that.

Another question is, take this example:

```python
from pipelines import pipeline

nlp = pipeline("question-generation")
nlp("42 is the answer to life, the universe and everything.")
=> [{'answer': '42', 'question': 'What is the answer to life, the universe and everything?'}]
```
Here the output gives an `'answer'` and a `'question'`.

Can you please tell me how to get the `answer` as well using the `question-generation` model directly from `huggingface` library?

Right now using this code, I can generate questions but not the answers...

```python
text = """
CHICKEN SAMOSAS costs <hl>$6.95<hl>. It has <hl>Crispy Wrappers Filled with Spiced Chicken<hl>. It is Served with Cilantro Dipping Sauce.
"""

enc = tokenizer([text], return_tensors="pt")
input_ids = enc["input_ids"]
attention_mask = enc["attention_mask"] # necessary if padding is enabled so the model won't attend pad tokens

tokens = singletask_model.generate(input_ids=input_ids, attention_mask=attention_mask,num_beams=8,num_return_sequences = 7)

out_ = []
for token in tokens:
  print(tokenizer.decode(token))
  out_.append(tokenizer.decode(token))

=> What does the SAMOSAS cost?
How much does the SAMOSAS cost?
What is the cost of the SAMOSAS?
What is the price of the SAMOSAS?
What is the cost of SAMOSAS?
What does the SAMOSAS have?
What does the SAMOSAS cost for?
```

**Comment by vidyap-xgboost** [comment]
@patil-suraj @psinha30 There's one more issue I'm facing with the `text` and `hl`.

If I give more than 2 `hl` in a text, the questions generated are weird. Like below.

```python
text = """
CHICKEN SAMOSAS costs <hl>$6.95<hl>. It has <hl>Crispy Wrappers Filled with Spiced Chicken<hl>. It is served with <hl>Cilantro Dipping Sauce.<hl>
"""

Output:

What is the SAMOSAS for what what??
What is the SAMOSAS cost what what??
What is the SAMOSAS for what??
What is the SAMOSAS cost what what what??
What is the SAMOSAS cost what what?
What is the SAMOSAS for what what??
What is the SAMOSAS for what what?
```

**Comment by psinha30** [comment]
> @psinha30 Thank you! This works and also, using `<hl>` solves the problem for texts it wasn't able to create questions. However, according to the examples given in the README file, we shouldn't be giving any highlights in the first place. I understand that @patil-suraj is working on resolving that.
> 
> Another question is, take this example:
> 
> ```python
> from pipelines import pipeline
> 
> nlp = pipeline("question-generation")
> nlp("42 is the answer to life, the universe and everything.")
> => [{'answer': '42', 'question': 'What is the answer to life, the universe and everything?'}]
> ```
> 
> Here the output gives an `'answer'` and a `'question'`.
> 
> Can you please tell me how to get the `answer` as well using the `question-generation` model directly from `huggingface` library?
> 
> Right now using this code, I can generate questions but not the answers...
> 
> ```python
> from transformers import pipeline
> from transformers import AutoTokenizer, AutoModelWithLMHead
> 
> tokenizer = AutoTokenizer.from_pretrained("valhalla/t5-small-qg-hl")
> singletask_model = AutoModelWithLMHead.from_pretrained("valhalla/t5-small-qg-hl")
> 
> text = """
> CHICKEN SAMOSAS costs <hl>$6.95<hl>. It has <hl>Crispy Wrappers Filled with Spiced Chicken<hl>. It is Served with Cilantro Dipping Sauce.
> """
> 
> enc = tokenizer([text], return_tensors="pt")
> input_ids = enc["input_ids"]
> attention_mask = enc["attention_mask"] # necessary if padding is enabled so the model won't attend pad tokens
> 
> tokens = singletask_model.generate(input_ids=input_ids, attention_mask=attention_mask,num_beams=8,num_return_sequences = 7)
> 
> out_ = []
> for token in tokens:
>   print(tokenizer.decode(token))
>   out_.append(tokenizer.decode(token))
> 
> => What does the SAMOSAS cost?
> How much does the SAMOSAS cost?
> What is the cost of the SAMOSAS?
> What is the price of the SAMOSAS?
> What is the cost of SAMOSAS?
> What does the SAMOSAS have?
> What does the SAMOSAS cost for?
> ```
> 
> Notice that it wasn't able to recognize the second `hl` as the answer.

Here is the code from pipelines where the whole process goes of getting the answer:
![Screenshot (229)](https://user-images.githubusercontent.com/44596136/91009784-ed112880-e5fe-11ea-9229-fc96b875e563.png)
It seems we could use only one hl tag.

**Comment by vidyap-xgboost** [comment]
Thanks for pointing out. Will follow this @psinha30

**Comment by patil-suraj** [comment]
@vidyap-xgboost ,
@psinha30 's answers are correct :+1: 
Thank you for answering these questions !

**Comment by vidyap-xgboost** [comment]
Thank you to you both @patil-suraj @psinha30 for patiently answering all the questions I had. I will close this issue now as I'm able to use `question-generation` directly from `transformers` library.
