### ISSUE TITLE
Questions generated don't make sense sometimes

### ISSUE THREAD

**Issue by vidyap-xgboost** [patil-suraj/question_generation#24]
I ran the following code on Colab:

```python
text1 = """
Chicken Samosas. Chicken Samosas costs <hl>$6.95<hl>."""

text2 = """
Chicken Samosas has <hl>Crispy Wrappers filled with Spiced Chicken<hl>.
"""

text3 = """
Chicken Samosas is served with <hl>Cilantro Dipping Sauce<hl>.
"""

from transformers import pipeline
from transformers import AutoTokenizer, AutoModelWithLMHead

singletask_tokenizer = AutoTokenizer.from_pretrained("valhalla/t5-small-qg-hl")
singletask_model = AutoModelWithLMHead.from_pretrained("valhalla/t5-small-qg-hl")

enc = singletask_tokenizer([text2], return_tensors="pt")
input_ids = enc["input_ids"]
attention_mask = enc["attention_mask"] # necessary if padding is enabled so the model won't attend pad tokens

singletask_tokens = singletask_model.generate(input_ids=input_ids, attention_mask=attention_mask
                                              , num_beams=2, num_return_sequences=2
)

out_ = []
for token in singletask_tokens:
  print(singletask_tokenizer.decode(token))
  out_.append(singletask_tokenizer.decode(token))
```

**Note:** I ran the second text.

Output is as follows:

```
What is assassssssssssss
What is assassasssssssss
```

They don't make sense. How to generate meaningful questions when we have only one sentence?

When I run first and third `text`, the outputs are as follows:

`text1`:
What is the cost of chicken Samosas?
What is the cost of Chicken Samosas?

`text3`:
What is served with? Chicken Samosas is served with?
What is served with? Chicken Samosas is served with what?

**Comment by vidyap-xgboost** [comment]
When I run the same code on other similar text like below:

```python
text4 ="Fresh Kale Salad. Fresh Kale Salad costs <hl>$6.95<hl>."

text5 = "Fresh Kale Salad has <hl>Apples, Marcona Almonds, Golden Raisins and Green Beans<hl>."

text6 = "Fresh Kale Salad is tossed with our <hl>Buttermilk-Black Pepper Dressing<hl>."
```

It gives me good output, like below:

`text4`:
How much does Fresh Kale Salad cost?
What does Fresh Kale Salad cost?
What is Fresh Kale Salad cost?

`text4`:
What does Fresh Kale Salad have?
What does Fresh Kale Salad has?
What does Fresh Kale Salad have?

`text6`:
What is tossed with the Fresh Kale Salad?
What is tossed with the Fresh Kale Salad with?
What is tossed with the Fresh Kale Salad tossed with?

**What could be the reason to perform so differently with similar type of content??**

**Comment by patil-suraj** [comment]
Hi @vidyap-xgboost, 

It's necessary to put spaces before and after special tokens so it gets treated as a single token, also the text should end with `</s>`.

With these changes I got following results.

```python3
text2 = """
Chicken Samosas has <hl> Crispy Wrappers filled with Spiced Chicken <hl> . </s>
"""

enc = singletask_tokenizer([text2], return_tensors="pt")
input_ids = enc["input_ids"]
attention_mask = enc["attention_mask"] # necessary if padding is enabled so the model won't attend pad tokens

singletask_tokens = singletask_model.generate(input_ids=input_ids, attention_mask=attention_mask
                                              , num_beams=2, num_return_sequences=2
)

out_ = []
for token in singletask_tokens:
  print(singletask_tokenizer.decode(token))
  out_.append(singletask_tokenizer.decode(token))

=> What type of wrappers does Chicken Samosas have?
What is the name of the Chicken Samosas?
```

**Comment by vidyap-xgboost** [comment]
@patil-suraj Thank you for the clear explanation! This helps me understand `question-generation` in a better way.

I think I can close this issue now.
