### ISSUE TITLE
Couldn't instantiate the backend tokenizer from one of: (1) a `tokenizers` library serialization file, (2) a slow tokenizer instance to convert or (3) an equivalent slow tokenizer class to instantiate and convert. You need to have sentencepiece installed to convert a slow tokenizer to a fast one.

### ISSUE THREAD

**Issue by Xyde** [patil-suraj/question_generation#53]
Hello, I used this model to generate question and it worked until 2-3 days ago:
https://huggingface.co/valhalla/t5-base-qg-hl

Now it returns the error message:
Couldn't instantiate the backend tokenizer from one of: (1) a `tokenizers` library serialization file, (2) a slow tokenizer instance to convert or (3) an equivalent slow tokenizer class to instantiate and convert. You need to have sentencepiece installed to convert a slow tokenizer to a fast one.

For some reason, the sample question works (what is the answer of the universe?), but anything "custom" returns with that message. Here is what I don't understand: the last commit was 5 months ago, so how come the error log appears now?

Here is the sentence I tried inputting: 
The bump is made of <hl>cartilage<hl></s>
Before I would get error log if the sentence was too long, but now even for short sentences like the above one it wouldn't even work.

**Comment by nicken** [comment]
@Xyde 
Can you tall me what happen and how to solve it? I get same probelm now

**Comment by nicken** [comment]
> @Xyde
> Can you tall me what happen and how to solve it? I get same probelm now

I slove it to `pip install transformers==3.0.0`

**Comment by daisylab** [comment]
Yes. I had same problem and I found that I used transformers 4.2. The solution was just same as @nicken  described. 

It will be helpful if we get an update code for transformers 4.2. Is there a plan for this?

**Comment by HenryJunW** [comment]
I got a error while evaluate valhalla/t5-base-qg-hl model using 'nlp = pipeline("question-generation", model="valhalla/t5-base-qg-hl", ans_model='valhalla/t5-base-qa-qg-hl', qg_format="highlight")'. 
**'AssertionError: You should supply an encoding or a list of encodings to this method. An encoding is the output of one the encoding methods of the tokenizer, i.e. __call__/encode_plus/batch_encode_plus.'**

Any help would be appreciated.
