### ISSUE TITLE
Unable to create tensor, you should probably activate truncation and/or padding

### ISSUE THREAD

**Issue by rashad101** [patil-suraj/question_generation#6]
Getting this error:
    "Unable to create tensor, you should probably activate truncation and/or padding "
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

Evan setting 'padding=True' 'truncation=True' is not helping

My whole code is as follows:
`
from pipelines import pipeline

text = "Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace."
nlp = pipeline("e2e-qg")
ques = nlp(text)
`

**Comment by patil-suraj** [comment]
Hi @rashad101 , what is your transformers version ?

**Comment by patil-suraj** [comment]
It's working with v3.0.0, you can try this [colab](https://colab.research.google.com/github/patil-suraj/question_generation/blob/master/question_generation.ipynb)

**Comment by rashad101** [comment]
I'm using v3.0. I guess it's conflicting with some other dependencies. I created another virtual env and it worked there. Thanks
