### ISSUE TITLE
How to get some kind of score for how confident the model is on that question?

### ISSUE THREAD

**Issue by vishwasgpai** [patil-suraj/question_generation#9]
Hi First of all thank you for this amazing repo. So much things to learn.
So my question was sometimes model generates some questions which are not grammatically correct maybe becoz of the answer highlighted word it is facing difficulties to form a questions on that. Is there a way to get a confidence score for each question it generates like question answering does?

**Comment by patil-suraj** [comment]
Thanks @vishwasgpai !
Yes, sometimes the generated questions are not grammatically correct, I'm looking for a way to automatically filter such questions, haven't found anything  yet. 

One way to check if the question is conceptually correct or not is s Roundtrip Consistency described in this [paper](https://arxiv.org/pdf/1906.05416.pdf), idea is to first 
1. extract an answer span
2. generate question for that answer
3. pass the question and context to a QA model and get answer
4. then compare the extracted answer with the answer returned by the QA model, if they overlap then we can say that the question is correct.

I'll update this issue, once I find a proper solution to this.

**Comment by vishwasgpai** [comment]
Yes, Actually that work around is a good. Thanks for it. I will experiment and update.
