### ISSUE TITLE
Want to finetune model on custom data!!!

### ISSUE THREAD

**Issue by sabhi27** [patil-suraj/question_generation#91]
Hi @patil-suraj, I looked at your work. It seems to be an awesome use case to solve in the real world. I am looking forward to finetuning the model on my custom data. I currently have a single CSV file with context, question, and answer as 3 columns in it.

I have some questions for you for finetuning model for the multi-task purpose (qa-qg) i.e. t5-base-qa-qg-hl:
1. Should I first transform this data to the same format as squad v1 is or is there an alternative way around it?
2. If the answer to the above question is "Yes, need to transform in same format", then if I do it successfully somehow then is there anything that I need to do explicitly to what Readme says.
3. After data formatting, **Prepare Data (prepare_data.py) -> training (run_qg.py) -> evaluation (eval.py)**. Is this the right sequence to follow for successfully training model?

Thanks in advance for response :)

**Comment by sabhi27** [comment]
Solved

**Comment by jacampo** [comment]
Hi, i'm interested in this, how did you solve it?

Thanks in advance 😊
